name: mehtrics-prod

services:
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
    restart: always
    volumes:
      - /opt/mehtrics/data/postgres:/var/lib/postgresql/data

  redis:
    extends:
      file: docker-compose.yml
      service: redis
    restart: always
    volumes:
      - /opt/mehtrics/data/redis:/data

  app:
    extends:
      file: docker-compose.yml
      service: app
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "80:8080"

  event-worker:
    extends:
      file: docker-compose.yml
      service: event-worker
    restart: always

  aggregation-worker:
    extends:
      file: docker-compose.yml
      service: aggregation-worker
    restart: always
